# Developer config
DEVELOPER_UID =
PING_DEVELOPER = f'<@{DEVELOPER_UID}>'
# Bot config
TOKEN = ""
BOT_ID =
# Guild config
LOUNGE = []
# Input control
BANNED_CHARACTERS = []
ALLOWED_CHARACTERS = ""
# Channel IDs
IP_MATCH_CHANNEL_ID =
VERIFICATION_CHANNEL_ID =
DEBUG_CHANNEL_ID =
SUB_CHANNEL_ID =
STRIKES_CHANNEL_ID =
NAME_CHANGE_CHANNEL_ID =
MOGILIST_CHANNEL_ID =
MOGILIST_LU_CHANNEL_ID =
SUGGESTION_VOTING_CHANNEL_ID =
SUGGESTION_LOG_CHANNEL_ID =
MOGI_MEDIA_CHANNEL_ID =
SQUAD_QUEUE_CHANNEL_ID =
LOUNGE_QUEUE_JOIN_CHANNEL_ID =
LOUNGE_QUEUE_SUB_CHANNEL_ID =
LOUNGE_QUEUE_LIST_CHANNEL_ID =
SUPPORT_CHANNEL_ID =
WELCOME_ENG_CHANNEL_ID =
WELCOME_JPN_CHANNEL_ID =
FAQ_CHANNEL_ID =
SQ_HELPER_CHANNEL_ID =

# Message IDs
ML_CHANNEL_MESSAGE_ID =
ML_LU_CHANNEL_MESSAGE_ID =
CATEGORIES_MESSAGE_ID =

# Role IDs
REPORTER_ROLE_ID =
ADMIN_ROLE_ID =
UPDATER_ROLE_ID =
TAGS_ROLE_ID =
CHAT_RESTRICTED_ROLE_ID =
LOUNGELESS_ROLE_ID =
PLACEMENT_ROLE_ID =
SUGGESTION_RESTRICTED_ROLE_ID =

# DB config
HOST = ""
PASS = ""
USER = ""
DTB = ""

# Jazzy's MKC config
JAZZY_MKC_NAME = ""
JAZZY_MKC_PASSWORD = ""
