# Developer config
DEVELOPER_UID = 0
PING_DEVELOPER = f"<@{DEVELOPER_UID}>"
# Bot config
TOKEN = ""
BOT_ID = 0
# Guild config
LOUNGE = []
# Input control
BANNED_CHARACTERS = []
ALLOWED_CHARACTERS = ""
# Channel IDs
IP_MATCH_CHANNEL_ID = 0
VERIFICATION_CHANNEL_ID = 0
DEBUG_CHANNEL_ID = 0
SUB_CHANNEL_ID = 0
STRIKES_CHANNEL_ID = 0
NAME_CHANGE_CHANNEL_ID = 0
MOGILIST_CHANNEL_ID = 0
MOGILIST_LU_CHANNEL_ID = 0
SUGGESTION_VOTING_CHANNEL_ID = 0
SUGGESTION_LOG_CHANNEL_ID = 0
MOGI_MEDIA_CHANNEL_ID = 0
SQUAD_QUEUE_CHANNEL_ID = 0
LOUNGE_QUEUE_JOIN_CHANNEL_ID = 0
LOUNGE_QUEUE_SUB_CHANNEL_ID = 0
LOUNGE_QUEUE_LIST_CHANNEL_ID = 0
SUPPORT_CHANNEL_ID = 0
WELCOME_ENG_CHANNEL_ID = 0
WELCOME_JPN_CHANNEL_ID = 0
FAQ_CHANNEL_ID = 0
SQ_HELPER_CHANNEL_ID = 0

# Message IDs
ML_CHANNEL_MESSAGE_ID = 0
ML_LU_CHANNEL_MESSAGE_ID = 0
CATEGORIES_MESSAGE_ID = 0

# Role IDs
REPORTER_ROLE_ID = 0
ADMIN_ROLE_ID = 0
UPDATER_ROLE_ID = 0
TAGS_ROLE_ID = 0
CHAT_RESTRICTED_ROLE_ID = 0
LOUNGELESS_ROLE_ID = 0
PLACEMENT_ROLE_ID = 0
SUGGESTION_RESTRICTED_ROLE_ID = 0

# DB config
HOST = "localhost"  # db host
PASS = ""  # db user
USER = ""  # db user
DTB = "lounge_dev"  # db name

# Jazzy's MKC config
JAZZY_MKC_NAME = ""
JAZZY_MKC_PASSWORD = ""
