from .handle_placement_init import handle_placement_init
from .handle_player_name import handle_player_name
from .handle_queued_mmr_penalties import handle_queued_mmr_penalties
from .handle_score_input import handle_score_input
from .handle_suggestion_decision import handle_suggestion_decision